baseURL = 'https://teddschreiner.de/'
languageCode = 'de-de'
language = 'de'
title = "Tedd Schreiner - IT-Systemadministrator"
theme = "pillar"
defaultContentLanguage = "de"

[markup.goldmark.renderer]
hardWraps = true

[params]
    cssColor = 2
    language = "de"

[params.personal]
    name = "Tedd Schreiner"
    role = "IT-Systemadministrator"

[params.social]
    email = "info@teddschreiner.de"
    phone = "+49 170 687 32 02"
    linkedin = "www.linkedin.com/in/teddschreiner/"
    github = "github.com/tschreiner"